### ISSUE TITLE
Inverted image controls unavailable

### ISSUE THREAD

**Issue by SirStefan02** [VixenLights/web.vixenlights.com#174]
Why don't you have options for manipulating the background image, like say when you have an image that appears normal in any viewer but is inverted in Vixen. It worked fine with a previous image, but now the image is upside down.  Don't know what to do about that.

**Comment by jeffu231** [comment]
Please create a proper bug report in the Vixen bug tracker. bugs.vixenlights.com. This is for the documentation site.
